name: sysmac_cmd
description: A simple command-line application.
version: 1.0.0
homepage: https://github.com/nils-ten-hoeve/sysmac_cmd
documentation: https://github.com/nils-ten-hoeve/sysmac_cmd/wiki

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.19.2
  build_runner: ^2.1.7
dependencies:
  collection: ^1.15.0
  archive: ^3.1.11
  fluent_regex: ^1.0.3
  xml: ^5.3.1
  documentation_builder: ^0.0.8
  recase: ^4.0.0
  petitparser: ^4.4.0
